apiVersion: v1
kind: Service
metadata:
  labels:
    name: couchbase
    role: service
  name: sync-gateway-service
spec:
  ports:
    - port: 4984
      targetPort: 4984
  selector:
    role: gateway
  type: 
    LoadBalancer